openapi: 3.0.1
info:
  title: Auth API
  description: API for authentication services
  version: 1.0.0

servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: Operations about user

paths:
  /test:
    post:
      summary: User login
      tags:
        - users
      operationId: login
      parameters:
        - name: user
          in: query
          schema:
            type: string
            minLength: 3
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string