openapi: 3.0.1
info:
  title: Auth API
  description: API for authentication services
  version: 1.0.0

servers:
  - url: http://localhost:8080
tags:
  - name: Users
    description: Users CRUD

paths:
  /user:
    post:
      summary: Create user
      tags:
        - Users
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Success

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string